configMap:
  endpointBase: /
  mapboxAdminBaseUrl: https://api.entur.io/mapbox-admin/v1/
  geocoderAdminBaseUrl: https://api.entur.io/timetable-admin/v1/geocoder/
  authServerUrl: https://auth.entur.org/auth/
  chouetteBaseUrl: https://rutedb.entur.org/
  timetableAdminBaseUrl: https://api.entur.io/timetable-admin/v1/timetable/
  mapAdminBaseUrl: https://api.entur.io/timetable-admin/v1/map/
  providersBaseUrl: https://api.entur.io/timetable-admin/v1/providers/
  eventsBaseUrl: https://api.entur.io/timetable-admin/v1/events/
  organisationsBaseUrl: https://api.entur.io/timetable-admin/v1/organisations/
  poiFilterBaseUrl: https://api.entur.io/timetable-admin/v2/poi-filter
  auth0Domain: ror-entur.eu.auth0.com
  auth0ClientId: AcbufyPib1kF5QOw8fgpeyqnbp2jWmLC
  auth0Audience: https://ror.api.entur.io
  auth0ClaimsNamespace: https://ror.entur.io/role_assignments

ingress:
  enabled: true
  loadBalancerIP: 104.199.93.228
  domainName: .entur.org