configMap:
  endpointBase: /
  mapboxAdminBaseUrl: https://api.entur.io/mapbox-admin/v1/
  geocoderAdminBaseUrl: https://api.entur.io/timetable-admin/v1/geocoder/
  chouetteBaseUrl: https://rutedb.entur.org/
  udugMicroFrontendUrl: https://netex-validation-reports.entur.org
  ninsarMicroFrontendUrl: https://line-statistics.entur.org
  timetableAdminBaseUrl: https://api.entur.io/timetable-admin/v1/timetable/
  mapAdminBaseUrl: https://api.entur.io/timetable-admin/v1/map/
  providersBaseUrl: https://api.entur.io/timetable-admin/v1/providers/
  eventsBaseUrl: https://api.entur.io/timetable-admin/v1/events/
  organisationsBaseUrl: https://api.entur.io/timetable-admin/v1/organisations/
  poiFilterBaseUrl: https://api.entur.io/timetable-admin/v2/poi-filter
  auth0Domain: auth2.entur.org
  auth0ClientId: AcbufyPib1kF5QOw8fgpeyqnbp2jWmLC
  auth0Audience: https://ror.api.entur.io
  auth0ClaimsNamespace: https://ror.entur.io/role_assignments
  defaultAuthMethod: auth0

ingress:
  enabled: true
  domainName: .entur.org