env: dev

replicas: 2


rollingUpdate:
  maxSurge: 1
  maxUnavailable: 1

resources:
  cpuLimit: 550m
  memLimit: 550Mi
  cpuRequest: 100m
  memRequest: 550Mi


configMapMount:
   name: ninkasi-config

image:
  identifier: ${artifact.metadata.image}
  imagePullPolicy: Always

service:
  http:
    externalPort: 80
    internalPort: 8000
