export const PROVIDER_LIST = 'PROVIDER_LIST'
export const REQUEST_PROVIDERS = 'REQUEST_POSTS'

export const RECV_ERROR = 'RECV_ERROR'
export const REQ_DATA = 'REQ_DATA'
export const RECV_DATA = 'RECV_DATA'

export const SELECT_SUPPLIER = 'SELECT_SUPPLIER'

export const ERROR_IMPORT_DATA = 'ERROR_IMPORT_DATA'
export const REQUEST_IMPORT_DATA = 'REQUEST_IMPORT_DATA'
export const SUCCESS_IMPORT_DATA = 'SUCCESS_IMPORT_DATA'

export const ERROR_EXPORT_DATA = 'ERROR_EXPORT_DATA'
export const REQUEST_EXPORT_DATA = 'REQUEST_EXPORT_DATA'
export const SUCCESS_EXPORT_DATA = 'SUCCESS_EXPORT_DATA'

export const ERROR_DELETE_DATA = 'ERROR_DELETE_DATA'
export const REQUEST_DELETE_DATA = 'REQUEST_DELETE_DATA'
export const SUCCESS_DELETE_DATA = 'SUCCESS_DELETE_DATA'

export const ERROR_BUILD_GRAPH = 'ERROR_BUILD_GRAPH'
export const REQUEST_BUILD_GRAPH = 'REQUEST_BUILD_GRAPH'
export const SUCCESS_BUILD_GRAPH = 'SUCCESS_BUILD_GRAPH'

export const ERROR_FETCH_OSM = 'ERROR_FETCH_OSM'
export const REQUEST_FETCH_OSM = 'REQUEST_FETCH_OSM'
export const SUCCESS_FETCH_OSM = 'SUCCESS_FETCH_OSM'

export const ADD_NOTIFICATION = 'ADD_NOTIFICATION'

export const REQUEST_FILENAMES = 'REQUEST_FILENAMES'
export const SUCCESS_FILENAMES = 'SUCCESS_FILENAMES'
export const ERROR_FILENAMES = 'ERROR_FILENAMES'
