name: Pull request build and deploy
'on': pull_request
jobs:
  build:
    if: '${{ github.event.pull_request.head.repo.full_name == github.repository }}'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7.0.1
      - uses: actions/setup-node@v7.0.0
        with:
          node-version: 24.20.0
          cache: npm
      - run: npm ci
      - run: npm run check
      - run: npm run test -- --coverage
      - run: npm run build
        env:
          REACT_APP_VERSION: ${{ github.sha }}
      - name: Inject dev env config
        run: cp build/config.dev.json build/config.json
      - name: Archive production artifacts
        uses: actions/upload-artifact@v7.0.1
        with:
          name: build
          path: |
            build

  preview_dev:
    needs: [build]
    permissions:
      contents: read
      pull-requests: write
      id-token: write
    uses: entur/gha-firebase/.github/workflows/firebase-hosting-preview.yml@v1.2.9
    with:
      gcp_project_id: ent-ninkasi-dev
      environment: dev
      build_artifact_name: build
      build_artifact_path: build
