name: Production maintenance mode
on: workflow_dispatch
jobs:
  prepare:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7.0.0
      - name: Copy maintenance mode file
        run: mkdir build && cp public/maintenance.html build/index.html
      - name: Archive maintenance artifact
        uses: actions/upload-artifact@v7.0.1
        with:
          name: maintenance-build
          path: |
            build

  deploy_prod:
    needs: [prepare]
    permissions:
      contents: read
      pull-requests: write
      id-token: write
    uses: entur/gha-firebase/.github/workflows/firebase-hosting-deploy.yml@v1
    with:
      gcp_project_id: ent-ninkasi-prd
      environment: prd
      build_artifact_name: maintenance-build
      build_artifact_path: build
